### ISSUE TITLE
No search type for [scan]

### ISSUE THREAD

**Issue by shiranp** [robbydyer/stash-query#15]
Encounterd the following error when using with elasticsearch 5.x:
<pre>
/usr/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error': [400] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"No search type for [scan]"}],"type":"illegal_argument_exception","reason":"No search type for [scan]"},"status":400} (Elasticsearch::Transport::Transport::Errors::BadRequest)
        from /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/base.rb:318:in `perform_request'
        from /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
        from /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/client.rb:131:in `perform_request'
        from /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-api-5.0.3/lib/elasticsearch/api/actions/search.rb:179:in `search'
        from /usr/lib/ruby/gems/2.3.0/gems/stash-query-0.1.3/lib/stash-query/query.rb:213:in `run_query'
        from /usr/lib/ruby/gems/2.3.0/gems/stash-query-0.1.3/lib/stash-query/query.rb:66:in `initialize'
        from /usr/lib/ruby/gems/2.3.0/gems/stash-query-0.1.3/bin/stash-query:71:in `new'
        from /usr/lib/ruby/gems/2.3.0/gems/stash-query-0.1.3/bin/stash-query:71:in `<top (required)>'
        from /usr/bin/stash-query:23:in `load'
        from /usr/bin/stash-query:23:in `<main>'
</pre>

Scan was removed from search types in favor of scroll with {"sort": ["_doc"]}.

[5.x Search type changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_search_changes.html#_literal_search_type_scan_literal_removed
)

**Comment by pteich** [comment]
I had the same problem with stash-query after upgrading to ES 5.x. Because I regularly do CSV exports from ES I wrote a similar tool in Go that works with the scroll API of newer ES versions.

https://github.com/pteich/elastic-query-export

It still misses some functionality but it's usable.
